[2023-12-28 14:56:17,090] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.transformar_data scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28 14:56:17,168] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.transformar_data scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28 14:56:17,169] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-28 14:56:17,171] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-28 14:56:17,172] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-28 14:56:17,392] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-27 00:00:00+00:00
[2023-12-28 14:56:17,462] {standard_task_runner.py:52} INFO - Started process 1080 to run task
[2023-12-28 14:56:17,482] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'transformar_data', 'scheduled__2023-12-27T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmp2_9l0cgk', '--error-file', '/tmp/tmpej03nej5']
[2023-12-28 14:56:17,501] {standard_task_runner.py:80} INFO - Job 12: Subtask transformar_data
[2023-12-28 14:56:18,617] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.transformar_data scheduled__2023-12-27T00:00:00+00:00 [running]> on host 98dcb739da71
[2023-12-28 14:56:18,997] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-28 14:56:19,253] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-27T00:00:00+00:00
[2023-12-28 14:56:19,262] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-27 0
[2023-12-28 14:56:19,468] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:98 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,485] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:99 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,499] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:100 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,529] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:103 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,564] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:104 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,594] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:105 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,644] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-28 14:56:19,795] {python.py:173} INFO - Done. Returned value was: None
[2023-12-28 14:56:19,892] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=transformar_data, execution_date=20231227T000000, start_date=20231228T145617, end_date=20231228T145619
[2023-12-28 14:56:20,026] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-28 14:56:20,232] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
