[2023-12-27 15:50:10,257] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.transformar_data manual__2023-12-27T15:50:00.342705+00:00 [queued]>
[2023-12-27 15:50:10,280] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.transformar_data manual__2023-12-27T15:50:00.342705+00:00 [queued]>
[2023-12-27 15:50:10,281] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 15:50:10,282] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 15:50:10,283] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 15:50:10,318] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-27 15:50:00.342705+00:00
[2023-12-27 15:50:10,327] {standard_task_runner.py:52} INFO - Started process 4443 to run task
[2023-12-27 15:50:10,335] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'transformar_data', 'manual__2023-12-27T15:50:00.342705+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmphdrgjkvu', '--error-file', '/tmp/tmpk5ixyvb3']
[2023-12-27 15:50:10,338] {standard_task_runner.py:80} INFO - Job 80: Subtask transformar_data
[2023-12-27 15:50:10,598] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.transformar_data manual__2023-12-27T15:50:00.342705+00:00 [running]> on host 44a36bef83ad
[2023-12-27 15:50:10,757] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-27 15:50:10,939] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T15:50:00.342705+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T15:50:00.342705+00:00
[2023-12-27 15:50:10,944] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-27 15
[2023-12-27 15:50:11,066] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:96 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,076] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:97 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,089] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:98 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,109] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:101 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,127] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:102 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,142] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather2.py:103 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,151] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 15:50:11,181] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 15:50:11,246] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=transformar_data, execution_date=20231227T155000, start_date=20231227T155010, end_date=20231227T155011
[2023-12-27 15:50:11,332] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 15:50:11,859] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
