[2023-12-12 04:09:55,829] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data manual__2023-12-12T04:09:33.823825+00:00 [queued]>
[2023-12-12 04:09:55,872] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data manual__2023-12-12T04:09:33.823825+00:00 [queued]>
[2023-12-12 04:09:55,873] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-12 04:09:55,874] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-12 04:09:55,875] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-12 04:09:55,944] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-12 04:09:33.823825+00:00
[2023-12-12 04:09:55,971] {standard_task_runner.py:52} INFO - Started process 465 to run task
[2023-12-12 04:09:55,989] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL', 'transformar_data', 'manual__2023-12-12T04:09:33.823825+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather.py', '--cfg-path', '/tmp/tmpcoclpvxs', '--error-file', '/tmp/tmpj1sdwyou']
[2023-12-12 04:09:55,994] {standard_task_runner.py:80} INFO - Job 6: Subtask transformar_data
[2023-12-12 04:09:56,412] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL.transformar_data manual__2023-12-12T04:09:33.823825+00:00 [running]> on host 9ceec7b750bf
[2023-12-12 04:09:56,723] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-12 04:09:57,334] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-12T04:09:33.823825+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-12T04:09:33.823825+00:00
[2023-12-12 04:09:57,469] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-12 4
[2023-12-12 04:09:57,763] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:93 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,771] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:94 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,780] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:95 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,795] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:98 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,800] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:99 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,808] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:100 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,813] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-12 04:09:57,836] {python.py:173} INFO - Done. Returned value was: None
[2023-12-12 04:09:57,883] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL, task_id=transformar_data, execution_date=20231212T040933, start_date=20231212T040955, end_date=20231212T040957
[2023-12-12 04:09:57,994] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-12 04:09:58,368] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
